version: "3.8"

services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:stable
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
