version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE=laravel
      MYSQL_ROOT_PASSWORD=root
      MYSQL_USER=laravel
      MYSQL_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_artisan
    working_dir: /var/www
    entrypoint: ["php", "artisan"]
    volumes:
      - ./:/var/www
    depends_on:
      - app

volumes:
  mysql_data:
